language: perl
sudo: false
perl:
- '5.12'
- '5.14'
- '5.16'
- '5.18'
- '5.20'
- '5.22'
- '5.24'
- '5.26'
notifications:
  slack:
    secure: L6ys7z8QuMkHiL1WFTv9EJ+5/jUAypzg2TSjuMw6r0xAEUvAtUm0hPeFQx03BOPtsJ67ZHifstQpVmeJk8+hMYuzuVOaoS7nYrQd+s3eiwzmnwt8OHdza8HPod6L5joOBlSUTEZvVDudsLiXgJipBHrDoyOPtQATZfuPWELwA0O5O/+pywcnzxPoWsaLFw9iXc62vDTg7a0Nb7XOzZvV/L+uSZvFgbuGH0aXDlrL6NtpmBRpwSOMGSyCTZyOt/jmH1qf4CXwi13c/Ks8l1RjMPmRNlsByDVn6JNDilBWF8Dti01Ysn+ks8S2d64XV+5YvIl5/fmCSggfArTa/YckXXQ1qHUFjbCfvyb+kDRgUh4JdMrtqwj4V+mGzSgMdUW82Is3Jtxq9Xgd2lnM/s4tx5WEduILFlgj8ExNP6nEwPo6Dt3hAMGizBG2JHdYA3v8zfJFhTeuXG+FLlRXcVnVBVCLbNmXRiXfR2Wl1kywqNJ4Ys6WXHWNVBEX1g0n8iAGWy/n4XCfxAafI/i+jlEEVdF9I8gYx//YcmGIOsiTQ4aSqTcAn61DYXUKo80D2YDC/X7F8am6s3gNUf96cw9GuAo6FMiES2WS+REayIoCNRetrWqi/TzJTcbeUPBb9sS7BI7PAQjGdB9U+zFp90SyBlCucWC7QLRrJyKA8VCaO6Y=
