language: perl
sudo: false
perl:
- '5.8'
- '5.10'
- '5.12'
- '5.14'
- '5.16'
- '5.18'
- '5.20'
- '5.22'
- '5.24'
- '5.26'
notifications:
  email:
    on_success: change
    on_failure: never
  slack:
    secure: CwvUd52cNGDs33rTVQ5DkdgEDf6JyifGqySBCJvp5wvFwkV6sObqInmpiNWVrxweZ4LoZayrBnFSjsFETrjwALU/SPdM/oqFqLUAjD/VGKj8GQiHlT+oaG9D3y3rgJ8qWjyx6dYkmh508k1pXGsW0aub0hFbTG+706Y+0UbWs7SFK5drd8xiM9MPVLW3yFGbT3NXFIUUywVAbIzs0vOco6AqD6xw6MaO7oPJo3vynn60EzrLbiHWSZRoF/lL5putzskM4/Ec3MYX7KpxjvWpQgKdcrtS2LHBTEFNTPCxGbWrzslYlVXLuGXR61HGzr/Do8pTpG5+cyuFCQayaxvbM5u65e7oWuFCxAqxGszE05SWhtEfXxRs/ZnudaEsJkmLqUHhtEaGftK8zNpkf1k2OYa0M6ZZOiE1ApjVOsOnFDbIKMKczRlkZlnkSeTyktUpq7xYne4DSfLNK2sNGYm9PftGjUt8a2HeJ5Byr5V261KPtzNrgxf2tnUSZ5sQIO9E0flodFmwo/PvbjG5/Wu+bQ4PVn9OTH6fGi7aLLSbiPomdLKbD0hanwvMjVxWmCSi8Nrh/vvnK36gp24dL3cKfSNDuy7Zv3AAuTijX6b+u2u0k9oK9mMBR+JgHo11C7sCYtdHF7Vd09v1GML9WCPcto4Uq0tPRXDtr79OX8UthPk=
