language: perl
sudo: false
perl:
- '5.8'
- '5.10'
- '5.12'
- '5.14'
- '5.16'
- '5.18'
- '5.20'
- '5.22'
- '5.24'
- '5.26'
notifications:
  slack:
    secure: UtkTD6/+8N02wqzBFr7k/YDSoYl97tOEU0qzO6bDgLOXFU6Hbo7kbES394r6KC574Z6bFXLNXltqn/NSJ25FxN1UuNiFGd+EakRetz04UQiIiO7f5W5F/t5NSZYwTfVsuUee5W55HILGtCdMPdXb0RoV8+4IJV5oYU0AlbdlTiMfQqn+Yqer/9NXrNxdS2sqC0IqwVnQdqf/lY6fN9lo1jNV+Wg1XtNzykkUr7gmO16Kw2ZH+S0un4IReyge+pmXBWmUs7kcjHyuVVkaDz7OkvlzWf+p6W9qpY4bPi4bH5rYOupZgsWBVly9m+wOWQpcTCphbV3RstUlF4w9W3f+D4Jv5PQxozTvsFRY9ddsmXtan5BWIFMLXjK7Mk+ki9YxUNGsMauyS22MHmqWdfs0GHAMichvTy43S11NGLSDukXCeNrvNtVKCYnxP+0tLIKEjKh72IuP8gEWW3Os8Q/dhLkkJQk9Gyw+bqCD8gfjpFLZnHt/E8MvVh1Al2OLc2sKYJENV0M52oGKZ8YiQWwg94yayWECnW/4Ishh+uOLz37x/VAIlO4AdLOXePAnx0kC6g648Y0oYNiOJHJJ1iJweDnMWwhLphgg0wil3FlRMT3DZi9GWw2G/YQIw2qWzSDJOvr7Zblk2+z1zCNQzdkuA1fng622E6p1/7R9XqcF1G0=
